# Generated by Django 5.2 on 2025-05-04 19:18

import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deffered_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True)),
                ('item_bought', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(default=10, null=True)),
                ('unit_price', models.IntegerField(default=10, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('date_of_payment', models.DateTimeField()),
                ('branch', models.CharField(max_length=50, null=True)),
                ('agent', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('stock_branch_name', models.CharField(max_length=50, null=True)),
                ('stock_type', models.CharField(max_length=50, null=True)),
                ('stock_time_of_arrival', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('supplier_contact', models.CharField(max_length=50, null=True)),
                ('stock_source', models.CharField(max_length=50, null=True)),
                ('unit_cost', models.IntegerField(default=10, null=True)),
                ('unit_price', models.IntegerField(default=0, null=True)),
                ('total_quantity', models.IntegerField(default=0, null=True)),
                ('issued_quantity', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('user_email', models.EmailField(max_length=25)),
                ('user_address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userprofile_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userprofile_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50, null=True)),
                ('seller', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(default=10, null=True)),
                ('amount_received', models.IntegerField(default=10, null=True)),
                ('issued_to', models.CharField(max_length=50, null=True)),
                ('unit_price', models.IntegerField(default=10, null=True)),
                ('date_of_sales', models.DateField(default=datetime.datetime(2025, 5, 4, 22, 18, 34, 687014))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
